stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-17
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/gitlab-ci-demo.jar

deploy-master:
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  stage: deploy
  script:
    - sshpass -V
    - export SSHPASS=$CI_USER_PASS
    - sshpass -e scp -o StrictHostKeyChecking=no target/gitlab-ci-demo.jar gitlab-ci@83.220.175.95:/home/gitlab-ci
    - sshpass -e ssh -tt -o StrictHostKeyChecking=no gitlab-ci@83.220.175.95 sudo mv /home/gitlab-ci/gitlab-ci-demo.jar /opt/tgbot/
