spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
    hikari:
      schema: "public"

  flyway:
    driver-class-name: org.postgresql.Driver
    url:
    user:
    password:
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      flywaydb:
        core:
          internal:
            license:
              VersionPrinter: OFF
      springframework:
        data:
          repository:
            config:
              RepositoryConfigurationExtensionSupport: OFF

application:
  telegram:
    token:
    username:
    voice:
      active: false
      download-path:
      wav-path:
      decrypted-path:
      ffmpeg-path:
  gpt:
    token:
