
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Step 1 - Checkout main branch from Github
      uses: actions/checkout@v3

    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Step 3 - Build with Maven
      run: mvn -B package -Pprod --file pom.xml
    
    - name: Step 4 - List of the files in /target directory
      run: ls -a ./target

    - name: Step 5 - Install SSH Client
      run: sudo apt-get install openssh-client -y

    - name: Step 6 - Copy SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan "${{ secrets.SRV_HOST }}" >> ~/.ssh/known_hosts

    - name: Step 7 - Transfer File via SSH
      run: scp -o StrictHostKeyChecking=no -P 22 ./target/tgapp.jar "${{ secrets.SRV_CREDS }}":"${{ secrets.DEST_FOLDER }}"