
name: Telegram Bot Assistant application CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Step 1 - Checkout main branch from Github
      uses: actions/checkout@v3

    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Step 3 - Build with Maven
      run: mvn -B package -Pprod --file pom.xml

    - name: Step 4 - SSH file transfer
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_RSA }}
        port: 22
        source: ${{ secrets.BUILD_FOLDER }}
        target: ${{ secrets.SERVER_JAR_PATH }}

#    - name: Step 5 - SSH execution restart scripts
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.SERVER_HOST }}
#        username: ${{ secrets.SERVER_USER }}
#        key: ${{ secrets.SERVER_RSA }}
#        port: 22
#        script: |
#          stop.sh
#          start.sh